#!/usr/bin/env node

/**
 * build-info.mjs — Generate src/core/buildInfo.ts with actual build metadata.
 *
 * Usage:
 *   node scripts/build-info.mjs
 *
 * This script:
 *   1. Reads the version from package.json
 *   2. Gets the current git commit hash
 *   3. Generates src/core/buildInfo.ts with this + build timestamp
 *
 * Call it before production builds (e.g., in CI/CD or prebuild script).
 */

import { readFileSync, writeFileSync } from 'fs';
import { execSync } from 'child_process';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

// 1. Read version from package.json
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
const version = pkg.version ?? '0.0.0';

// 2. Get git commit hash
let gitCommit = 'unknown';
let gitBranch = 'unknown';
try {
  gitCommit = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
  gitBranch = execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf-8' }).trim();
} catch {
  // Not a git repository or git not available
}

// 3. Build timestamp
const buildTime = new Date().toISOString();

// 4. Generate output
const content = `/**
 * Build information — AUTO-GENERATED by scripts/build-info.mjs.
 * Do not edit directly. Re-run \`node scripts/build-info.mjs\` to update.
 */

export const BUILD_INFO = {
  version: '${version}',
  gitCommit: '${gitCommit}',
  gitBranch: '${gitBranch}',
  buildTime: '${buildTime}',
} as const;
`;

const outPath = join(root, 'src', 'core', 'buildInfo.ts');
writeFileSync(outPath, content, 'utf-8');

console.log(`✅ Build info generated:
  version:   ${version}
  commit:    ${gitCommit}
  branch:    ${gitBranch}
  buildTime: ${buildTime}
  output:    ${outPath}`);
