/**
 * Build information — AUTO-GENERATED by scripts/build-info.mjs.
 * Do not edit directly. Re-run `node scripts/build-info.mjs` to update.
 */

export const BUILD_INFO = {
  version: '0.1.0',
  gitCommit: 'unknown',
  gitBranch: 'unknown',
  buildTime: '2026-07-19T02:40:36.646Z',
} as const;
